language: cpp
matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - COMPILER=gcc
  - os: osx
    osx_image: xcode7.2
    compiler: gcc
    env:
      - COMPILER=xcode7.2
  - os: windows
    env:
      - VS

    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
   
    # Add stuff for Python3 tests as well
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda;
      elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
        choco install miniconda3 --params="'/AddToPath:1'";
        export PATH="/c/tools/miniconda3/scripts:/c/tools/miniconda3/:$PATH";
      fi
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --set auto_update_conda no
    - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then conda update -q conda; fi
    - source activate
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
        sudo apt update;
        sudo apt install gcc-6 g++-6 -y;
      fi

install:
    - conda install boost eigen rbdl dlib-cpp lapack numpy pytest swig  -c conda-forge
    - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
        conda install ipopt -c conda-forge;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
        conda install lcov -c conda-forge;
      fi
      
script:
    ############################################################################
    # Build main and tests
    ############################################################################
    # Download, compile and test core
    - mkdir -p build
    - cd build
    # Perform tests on all platform, but only perform code coverage on Linux
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
        cmake ${CMAKE_OPTIONS} -DCMAKE_INSTALL_PREFIX=$HOME/miniconda/ -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON -DBUILD_EXAMPLE=OFF -DMODULE_ACTUATORS=ON -DMODULE_MUSCLES=ON .. ;
        make;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        cmake ${CMAKE_OPTIONS} -DCMAKE_INSTALL_PREFIX=$HOME/miniconda/ -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_EXAMPLE=ON -DMODULE_ACTUATORS=ON -DMODULE_MUSCLES=ON .. ;
        make;
      elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
        cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=/c/tools/miniconda3/ -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_EXAMPLE=OFF -DMODULE_ACTUATORS=ON -DMODULE_MUSCLES=ON -DBINDER_PYTHON3=ON ..;
        cmake --build ./ --config Release;
      fi
    # Only do the coverage on Linux, but run the test anyway to get a nice output
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cp -r test/models/ .;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        cd test;
      elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        cd test\\Release;
        xcopy ..\\models .\\models\\;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
        make biorbd_coverage;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        ./runUnitTests;
      elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
        ./runUnitTests.exe;
      fi
    - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then 
        cd ..;
      fi
    - ctest
    
      # Test if biorbd can be compile on the python binder
    - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then 
        cmake ${CMAKE_OPTIONS} -DCMAKE_INSTALL_PREFIX=$HOME/miniconda/ -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_EXAMPLE=OFF -DBINDER_PYTHON3=ON ..;
        make install;
      else
        cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=/c/tools/miniconda3/ -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_EXAMPLE=OFF -DBINDER_PYTHON3=ON ..;
        cmake --build ./ --config Release --target install;
      fi
    - python -c "import biorbd"    

after_success:
    # Uploading report to CodeCov
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
        cd ${TRAVIS_BUILD_DIR};
        lcov --directory . --capture --output-file coverage.info;
        lcov --remove coverage.info '/usr/*' --output-file coverage.info;
        lcov --list coverage.info;
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports";
      fi

notifications:
    email:
        on_success: never
        on_failure: always

