name: Publish MATLAB binaries

on: 
  release: 
    types: [published]

env:
  BUILD_FOLDER: build
  EXAMPLES_FOLDER: examples

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/biorbd_eigen
          # - os: macos-latest
          #   label: osx-arm64
          #   prefix: /Users/runner/miniconda3/envs/biorbd_eigen
          - os: macos-13
            label: osx-intel
            prefix: /Users/runner/miniconda3/envs/biorbd_eigen
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\biorbd_eigen
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: biorbd_eigen
          environment-file: environment_eigen.yml
        
      - name: Print mamba info
        run: | 
          mamba info
          mamba list
      
      - name: Setup Linux dependencies
        run:   |
         sudo apt update
         sudo apt install libstdc++-11-dev
        if: matrix.label == 'linux-64'
        
      - name: Install extra common dependencies
        run: | 
          mamba install cmake git pkgconfig swig pytest -cconda-forge
          mamba list
          git submodule update --init --recursive

      - name: Install MATLAB on WINDOWS, LINUX and MACOS-Intel
        uses: matlab-actions/setup-matlab@v2
        with: 
          cache: true
        if: matrix.label != 'osx-arm64' 

      - name: Install MATLAB on MACOS-Arm64
        uses: matlab-actions/setup-matlab@v2
        with:
          # The version of MATLAB of R2024a does not contain MX_LIBRARY
          release: R2023a
          cache: true
        if: matrix.label == 'osx-arm64'

      - name: Build biorbd on UNIX
        run: |
          MAIN_FOLDER=`pwd`
          cd
          HOME=`pwd`
          cd $MAIN_FOLDER
          CONDA_ENV_PATH=$CONDA/envs/biorbd_eigen
          mkdir -p $MAIN_FOLDER/$BUILD_FOLDER
          cd $MAIN_FOLDER/$BUILD_FOLDER
          cmake -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DMATH_LIBRARY_BACKEND="Eigen3" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_TESTS=OFF -DBUILD_DOC=OFF -DBUILD_EXAMPLE=OFF -DMODULE_ACTUATORS=ON -DMODULE_KALMAN=ON -DMODULE_PASSIVE_TORQUES=ON -DMODULE_MUSCLES=ON -DBINDER_MATLAB=ON -DMatlab_biorbd_eigen_INSTALL_DIR=$HOME ..
          make install -j${{ steps.cpu-cores.outputs.count }}
          cd $MAIN_FOLDER
        if: matrix.label != 'win-64'
      
      - name: Build biorbd on WINDOWS
        run: |
          MAIN_FOLDER=`pwd`
          CONDA_ENV_PATH=$CONDA/envs/biorbd_eigen
          mkdir -p $BUILD_FOLDER
          cd $BUILD_FOLDER
          cmake -G"Visual Studio 17 2022" -Ax64 -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DMATH_LIBRARY_BACKEND="Eigen3" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_DOC=OFF -DBUILD_EXAMPLE=OFF -DMODULE_ACTUATORS=ON -DMODULE_KALMAN=ON -DMODULE_MUSCLES=ON -DBINDER_MATLAB=ON -DMatlab_biorbd_eigen_INSTALL_DIR=$HOME ..
          cmake --build . --config Release --target install -j${{ steps.cpu-cores.outputs.count }}
          cd $MAIN_FOLDER
        if: matrix.label == 'win-64'

      - name: Build MATLAB archives on UNIX
        run: |
          cp -r $HOME/biorbd_matlab .
          zip -r biorbd_eigen_matlab_${{ matrix.label }}.zip biorbd_eigen_matlab
        if: matrix.label != 'win-64'

      - name: Build MATLAB archives on WINDOWS
        run: |
          7z a biorbd_eigen_matlab_${{ matrix.label }}.zip $HOME/biorbd_eigen_matlab
        if: matrix.label == 'win-64'

      - name: Upload files to a GitHub release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "biorbd_eigen_matlab_${{ matrix.label }}.zip"
          update_latest_release: true
          verbose: true
          overwrite: true
